version: '3'

services:
  web:
    container_name: web
    restart: always
    build: .
    ports:
      - "5000:4000"
    links:
      - mongo
    volumes:
      - .:/usr/src/app
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    logging:
      driver: none
